#!/bin/bash

set -e
cd "$(dirname "$0")"

# The packages to be built. Must be topologically sorted w.r.t dependencies.
pkgs=(
  k3s-bin
  alac-git
  nqptp-git
  shairport-sync-git
  swift-bin
  yay
)

if [ "$(uname -s)" != Linux ]; then
  echo "$0 must run on Linux!"
  exit 1
fi

echo "==> Setting up build directory"
builddir="$PWD/build"
mkdir -p "$builddir"

echo "==> Building the packages"
for pkg in "${pkgs[@]}"; do
  (
    cd "$pkg"

    # Build the package
    PKGDEST="$builddir" makepkg -si --noconfirm

    # Copy the generated .SRCINFO and (potentially) autobumped PKGBUILD
    buildsrcdir="$builddir/src/$pkg"
    mkdir -p "$buildsrcdir"
    makepkg --printsrcinfo > "$buildsrcdir/.SRCINFO"
    cp PKGBUILD "$buildsrcdir"
  )
done
