#!/bin/bash

set -e
cd "$(dirname "$0")"

for tool in updpkgsums strip git; do
  if ! command -v "$tool" > /dev/null; then
    echo "This script requires $tool on your PATH!"
    exit 1
  fi
done

echo "==> Reading packages"
pkgs=()
while IFS= read -r line; do
  if [[ "$line" != "#"* ]] && [[ -n "$line" ]]; then
    pkgs+=("$line")
  fi
done < packages.txt

echo "==> Updating derived info"
for pkg in "${pkgs[@]}"; do
  echo "--> $pkg"
  (
    cd "$pkg"

    updpkgsums
    makepkg --nobuild --noprepare --nodeps # Autobump VCS versions
    makepkg --printsrcinfo > .SRCINFO
  )
done
